import "./core.js";
const AJ = globalThis.AJ; let ok = 0, fail = 0;
const t = (n, c) => { if (c) ok++; else { fail++; console.log("FALHOU:", n); } };
const hdr = "PODER JUDICIÁRIO DO ESTADO DE GOIÁS";
const corpos = ["Trata-se de ação indenizatória em que o autor alega que o contrato foi", "celebrado mediante fraude.", "A ré contestou.", "Houve réplica."];
const out = AJ.cleanPages(corpos.map((c, i) => [hdr, c, "Documento assinado eletronicamente por FULANO", `Pág. ${i + 1} de 4`].join("\n")));
t("limpeza", !out.includes(hdr) && !out.includes("assinado") && out.includes("contrato foi ⟦Pág. 2⟧ celebrado"));
const autos = "Processo 5272040-93.2021.8.09.0115. Citação em 12/03/2022. R$ 15.000,00.";
t("fidelidade ok", AJ.verificarFidelidade("5272040-93.2021.8.09.0115 em 12/03/2022 R$ 15.000,00", autos).length === 0);
t("fidelidade erro", AJ.verificarFidelidade("5272040-93.2021.8.09.0116 R$ 15.500,00", autos).length === 2);
const m = AJ.mergeDossies([{ numeroProcesso: "123", pedidos: [{ litisconsorte: "Ana", descricao: "Dano moral" }] }, { pedidos: [{ litisconsorte: "Bruno", descricao: "Dano moral" }] }]);
t("merge litisconsortes", m.pedidos.map((p) => p.id + p.litisconsorte).join() === "P1Ana,P2Bruno" && m.numeroProcesso === "123");
t("nao apreciados", AJ.pedidosNaoApreciados(m, "Julgo [P1] procedente").map((p) => p.id).join() === "P2");
t("resumo", AJ.resumoExecutivo(m).includes("[P2] Bruno"));
const s = AJ.parseSeries("2025-01;1;1\n2025-02;1;1,5\n2025-03;1;0,5");
const r = AJ.calcularConsectarios({ principal: 1000, inicioCorrecao: "2025-01", inicioJuros: "2025-02", fim: "2025-03", ...s });
t("consectarios", Math.abs(r.corrigido - 1030.3) < 0.01 && Math.abs(r.juros - 5.15) < 0.01);
const txt = Array.from({ length: 400 }, (_, i) => `Parágrafo ${i}. Texto.`).join("\n\n");
const ch = AJ.chunkText(txt, 1500); t("chunk", ch.at(-1).endsWith("Parágrafo 399. Texto.") && ch.length > 4);
t("rank", AJ.rankPrecedentes("desconto indevido benefício previdenciário dano moral", [{ enunciado: "Desconto indevido em benefício previdenciário gera dano moral", palavrasChave: ["desconto indevido"] }]).length === 1);
t("paragrafos", AJ.paragrafosDensos("x".repeat(300) + "\n\n## T\n\n" + "y".repeat(300)) === 2);
t("secao", AJ.secao("## RELATÓRIO\na\n## FUNDAMENTAÇÃO\nb\n## DISPOSITIVO\nc", "FUNDAMENTA", "DISPOSITIVO").includes("b") && !AJ.secao("## RELATÓRIO\na\n## FUNDAMENTAÇÃO\nb\n## DISPOSITIVO\nc", "FUNDAMENTA", "DISPOSITIVO").includes("c"));
const pz = AJ.calcularPrazo("2025-12-18", 15);
t("prazo CPC com recesso", pz.vencimento === "2026-02-09");
t("prazo corrido", AJ.calcularPrazo("2026-03-02", 5, [], false).vencimento === "2026-03-09");
console.log(`${ok} ok, ${fail} falhas`);
